AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: amplify/functions/chat
      Handler: ./dist/handler.handler
      Runtime: nodejs22.x
      Timeout: 30
      Environment:
        Variables:
          NODE_ENV: development
          DEV_SUPABASE_URL: http://host.docker.internal:54321
          DEV_SUPABASE_SERVICE_ROLE_KEY: dummy-key
          OPENAI_API_KEY: dummy-key
      Events:
        ChatApi:
          Type: Api
          Properties:
            Path: /chat
            Method: post
            RestApiId: !Ref ChatApi

  ChatApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'POST, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'http://localhost:5173'" 